apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-meta-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: lvms-vg1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: lvms-vg1
