apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: garage
spec:
  serviceName: garage
  replicas: 1
  template:
    spec:
      containers:
        - name: garage
          image: dxflrs/garage:v2.1.0
          ports:
            - name: s3-api
              containerPort: 3900
            - name: rpc
              containerPort: 3901
            - name: web
              containerPort: 3902
            - name: admin
              containerPort: 3903
          volumeMounts:
            - name: config
              mountPath: /etc/garage/garage.toml
              subPath: garage.toml
            - name: rpc-secret
              mountPath: /etc/garage/secrets
              readOnly: true
            - name: meta
              mountPath: /var/lib/garage/meta
            - name: data
              mountPath: /var/lib/garage/data
          env:
            - name: GARAGE_CONFIG_FILE
              value: /etc/garage/garage.toml
            - name: GARAGE_ALLOW_WORLD_READABLE_SECRETS
              value: "true"
      volumes:
        - name: config
          configMap:
            name: garage-config
        - name: rpc-secret
          secret:
            secretName: garage-config
            defaultMode: 0600
        - name: meta
          persistentVolumeClaim:
            claimName: garage-meta-pvc
        - name: data
          persistentVolumeClaim:
            claimName: garage-data-pvc
