apiVersion: v1
kind: Service
metadata:
  name: quay-metrics
  namespace: quay
  labels:
    app: quay-metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
    prometheus.io/port: "9091"
spec:
  ports:
    - name: metrics
      port: 9091
      targetPort: 9091
      protocol: TCP
  selector:
    app: quay
  type: ClusterIP
