apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quay-metrics-monitor
  namespace: quay
spec:
  endpoints:
    - port: metrics
      interval: 30s
  selector:
    matchLabels:
      app: quay-metrics
