apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
stringData:
    client_id: ENC[AES256_GCM,data:BndjDofP8yyiVWg55oPBZLw=,iv:DKun+k4NDeF/zSyiAh2X0+s/K4HHsiDKOM8/gzRMF7w=,tag:SC0UbOVN6UIc2LKCGGiWEA==,type:str]
    client_secret: ENC[AES256_GCM,data:tG2A4rmu3z1O96W6+uKTVJ8pHZ/R6y3rDdgPEO0p/kgmqRcYivnH/wMX3TduQeEDbu36qfxG64Qxerir5oTfxQ==,iv:yXAZihUSENcfJ6Tw+2mvW8izUAN3En1J8r8TFBcQytM=,tag:vL7As8LftJZAfYawuB4iEg==,type:str]
sops:
    age:
        - recipient: age1jqn3xexdp75t7mgn4nyl3jhnqgsvxmnxpxu3c9x8zs27k439v9yqja32v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRFkyTzJZQTgvR1dCVDhs
            Ym4vdjZmcm5EblFKalU2TTJvTzFkOU1uc0E0CjFYcjdCWjR5eDEvczVYc0hKNGc2
            RHdGUWtmL25NZWl3VC82Vi9nbEFxeGsKLS0tIExuSEZ6SVpMamJkWTEwaUx2Y2hB
            djQ1a1NPMGxEbHVabVBIcHZHVmRkSWMKoYTeH9pX08p0EPKYBxQg4OANgd4D25O7
            y+9yAwUp1j7XmKf/+0qxPsjv6Klsnzqf2/dRiAK6W7VyTje/RkpM7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T16:33:52Z"
    mac: ENC[AES256_GCM,data:ErV6puoMPpCIs2A2XTDpf8BAZpIAfSlAHIImky1dsKWRUjCBsUBErq96RP0t1FuHbB2WPqbFO+8VzHABz8rsIqbKdg2bqbt96z4VEAIVo030hFElKKTIYYp7GIaYYh4SExPB8ifQqWRgrrapbB5dbjS6x5vuASkmBN901ZYk5+o=,iv:nUUI2OZNO5R1vvfZ3bPMByhqlFvrczJDZDfUri44B/c=,tag:PIbuzDsFxeIW2mNjQp7yBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
