apiVersion: v1
kind: Secret
metadata:
    name: config
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:bVxEIVnAVbn/elqyXeytKrLv8hcjnU4JAP6ff62Lfy4Xp64f6GjoTbFzqvzia7JMcQ3TYD8r39p8X7pfuQggk9lTdxDDYUMVvyMEVF8llNZ8BdealhGHI1/82jDRq2mtoTTRPa5PcftYpORJdH5Df343Q3qtTM1uRciYEoTeOUMmdsBm8znKix8/Cbc9icZJDsFhi4b2DuBtzylZ5MMYXtLk6i8q6Y6/eCyaRXqBdFF19sZkzbCauMZPxYT1tGrISF7U91XxOrT+2jmEFJtRDtt2txjUcp2OO7syRTNZOIf1pcxvpKTMtJHYayZfKoGm8nKazaYsy9jdZeBFzBaKrpu6L9UhayHNpmnbFQYo7zuIoFIDBl3pMCjmE7vJNQGQNRTs4mV1yhwjtq7VMqBsZj/Cqcw4ppW8KVFPnYOFjDnlg2wDLDA/gNBqqlsBhkgP9ijaw52WjRmR1SUYnaBCUbD+EoCOKObpfM9EUr4NEWuOPtkJQt02cYO2sfu+dnDhvchHjMpEMsYDyYwlNShZA3bes7dj8hvAnL3u20UsVtaTbn2cWqUMXSJH3VimLCxp6y3vI+bhEyctECvRylGPszF7bbIFiXVd8o/Pb+ggwspyJ31jpZwE6mKHkfer1y/1keXXIu9Fo3EEHy86MlGZtOAoYTgP4ZYbFTDWD3ADvMkYWHz4joCiEGAHYn+s56UDPB59MCdIOIIv3bb+W1Qww9uaXCVI0L8Vhmq78H4RHuzpNZ4a0/XnpIqEE1m2SoqNgC3JPZeVZU6L28I/Si9xAYuO3kLgvBYdhdHD7nUzmZpffHwqaC51MozqMhOXmdyHkg8F+iAEsLnSOCR56El7p3QsG6djRN5IX3Z/64tR8ON5mlYRzPSnYyh0kKkF4k/unggLqIsfQ4ffgNLJvr619f4pQWCM+Wk/DO4qC4rGVd+GmXfoNs6Tp0v1cQPnqD2fOA08FMskmToFJMyJcw+VEp1ayubXO7DWSelLao2LG8wZFVj1QFgw/ifFosYwwHOVdZBcKE+nFo4OEZH+k2GK4Ttpf9Gk3wbliQ97VF30jjexEEIGpcpG2fTi2chPZ1Pt6coCrLn0ytBmNfbQOan1RRg+4gB8TCzT33kDG8hq9PxqJTN4rNKVBrDKzRc8c6PUI/fznLz6KlVpmSvlCxc6440KXbfppogs1iEEVabv6kRfMrjM6CDlmqUuSkC397CYDs+cYr+vRgEZnxxfq78Ds5mAAhpgYSmii8yAX9Sdjvosu+M/Ojlcl0HNCGwwOUqB/lZtvyM8VKS4TYdn4SM2UmdhVTrO+mT8bqBybwoGzZ8aSd+V8r4LGIz1jdUlm1n/9WpL1Tu6dblP1e7ES2g64g==,iv:7ksjC6LQB2TX1HdpXEE7tvTLjwPmHFzH2tu4f8JNePQ=,tag:PpUGdqDqGC/JpL7prCf1yg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaL01BVitVTnRGNUFjaWFy
            cUFXVzdycFhRbDNHRllMYU9UVWpmbWwrTlNRCmprZ3hyTG5ja2NUbWZqUnJ3QmNz
            MEp4KzNDZUFLdEFMa0xCdGhLU2UyTncKLS0tIGtORkZCM1piYmJEbDk5eGh1bVVI
            NFRzalpNTk5qQTRkd3VzcDUxVm1lb28Ke7ltlZuRgR+HfVepEHhcixzCndvaAle+
            kyTkZHQays+2MQvK8zXFaU92Us3kHR0VQtgDe0brvGAV1IvseCyfOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jqn3xexdp75t7mgn4nyl3jhnqgsvxmnxpxu3c9x8zs27k439v9yqja32v3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T23:49:51Z"
    mac: ENC[AES256_GCM,data:EtLbkKWjaBgMET4051xnIBpJQWY5ZfPyS89yUBlfGGTpXI3In4buTh0J32jmkRzgmdM/VWwYa0x+bJs14SgOL2RXEhUl9QbC1GHKoZ5fDUnF02n9X6ofFoRySsekL7rtDRIKh8O/+Xz37L9Zgg3VTgVtC53HT5WKumcIX5gxSkc=,iv:1YZ+Xl4/Qzih34Q3hxFpyruH6/9oxI5WE4lEAq8RwI0=,tag:WTEXw2xgUYhRebh20p87lw==,type:str]
    version: 3.13.1
