apiVersion: v1
kind: Secret
metadata:
    name: config
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:Nm60bcrA3NGWVo7GFHus4ennqZ3SilGNCPnaaMNe6ziASiNjQdGyfVLn5TUdB4sc0WL57M4kAYx/HwRMaOc6Z1wwNpe7ljZyx3LvOerCiFM6Yoln+wzgmqUSqTMJzYMZsoHU8rD9bp0E533dCuGn1Q+6uz3HrLxvLtKTCtXHBI2WoZtyN8yHopOVjKD98LTMP7yKvBcbsMPkAq8FUqOWLNTW730k4KnV9hO8lMBu/gme0fHIsiriKtIfweQQt3/LbvXMw+MOilpoJkTu9GcIvEs/SNeDmUZLRSK/NZ6XNKUeC4aC8UIXGo0m+bSkWGEVkXmhozMtKActXZ6LjavDA60C3Gt2EaEtp9YCLI/ykwSHM1IKUncxklmTEDYkRHRiab8Mx6lJ76sZcarzyncoyvu0g+isjFV3V9DkpI20rsGAMCvP2+cLxT/a3VTJ+HeFcUD3zq+HtMr+5WdDRBgE4M4KQ3kOVJScCMAbIQGINTUQlgnxRQyBv0rRHmbVyhIQQndpNQm9ktvGWz0LMNSaelK43iUJA8UZ53pRsIe+t2gM6dmad+WwKXqWS6vFHYMaAl+/6rOu1ooPh877pc8TxM2c+dUQ+36XM1VJWDyNdH+5132QpGQm0WnKn/GkZKhWFBDNJFzfKZmCowckYchOCr/pIXdvfDXmovPeqN0V9Ka600CtZIxPiVhD4mC3HMi27OpMRtNZJi3ya2CtaFJnwjXgmyokCpmbY5i0m7BgCzoOcywjhGgcARuQC3E6+l8urxIEnnpJFJtYqV/xrrOV/LpgshtCxnroetgXXXTWZTKHqxEsQZpZgvm0Ehi549shX4f47rXfqjWzqhcQR+hN0COfNUxFMMmDh5IJLPH79ZZCjtTCgIgnhli/eVNgcRCV2Me06eKLwsST0GtNhDkGckwtZaYjY7m3zrE/5xmRj3hL8FT0XGnXLbjBjjZFr6L+otwN05NbZKIIwOorS8TnRIul5dmRn7A3YL9Nu7UdeIC6o+qJ6OdJaXYeu4ur3jkvwp+OgIOwLCgRVPgQRWJNV7afhiEKXsm1Xu6djlX2Ag4PbZZf5P5CCDOHX3Gb+bGPhJ3cuJuekKA9dDGVRH+ONuZb0d2xRmnyM29qBJveO3jYicdl0BmoMhULTcD3WhPx0RVAlTtxnVPBGAYfqfDYmhfPM7bGXW+JEXhQhsQt4R3xj5VmzGHuvW4tZ4MMCb1Rte8Wor9YfkM9+YLgKnBoSlCmlntUzEMyEBfCgZ87AinHKC1/L7YmsI7vs+MMGC5bpMbASW5hvPivIO9WkeQrJnScXkoy3ar6vVTjxB8LSe3ZH4yngx+2Xi8oqmsC/LysOqpqRy4M/fHSpxmOtP7L,iv:3NFPXG0a2qe1WSUT4PuX1J1mgxzNkqGHqI8nX0ZnBk8=,tag:uMVU5gVpWvyKCMnsu5VjCQ==,type:str]
sops:
    age:
        - recipient: age1jqn3xexdp75t7mgn4nyl3jhnqgsvxmnxpxu3c9x8zs27k439v9yqja32v3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQ2R2N1E5amJSK3dWbmQ5
            RldZcGhlSG1yOVN5eVpSNlIzSVlqUW4vS0VRCmYvM2JBL05QS3lXWDZQTXA1V1JB
            a2xidEhqR0lpc1hINmpqWDV3cy9uMm8KLS0tIDV2enFhZGRuRTlNNW05SUhlL2hj
            YTEzNkZjY0E2RStYbExsV0oveUMyN00K54suf+M921ZiU+w0kRHUHODbYhvJDol1
            tMNExz/l8aoJYoSYTMJCXKgAVjRJSBeUIR/MAlpQyNOt2FW8FP/jvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T20:36:33Z"
    mac: ENC[AES256_GCM,data:eKKM4ZvtWfSHAdszVh9kl3EYc3YZ5YLRkmXwi1ngcoWKICrRE2LfGAiPqLTqguUbTK04Z+G2fUvon4wYxOP6Fu3M+s+xlCieaH/A9myRqVHmwad3npNkIixQ+nyhKt6sNNFLb80NaRanpx2RPfW3b/v/IQqK3ju0CzP3RLlrupQ=,iv:/EwgQNikUX9SFROGg3u9UDmT5op+4iI6OAN83aMeT2Q=,tag:uepAW58FfxzBVY2b0q0JMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
