apiVersion: v1
kind: Secret
metadata:
    name: config
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:ytsGUh7dd1Tkg+0AXPRMLYG7rAJ2PxwMXoImIZpJKasI39sAi02X6rA0TmP8oYUUDbePbyVTThpL7yjzzF183medJPbAzjeoFELbB3J1MBVIHkBKjBnjPQFBag4D6xQxCmbrw9oJgiNcXKECzU/scMJrsMyUVihPRj0SEzG6YcNORqS8yqzxTQsPDtBhpSMOi6uHQFkN4Mj+626KGiwq/5PGugADVRbl5z7EtEyBtYzlG9QijLhwJGq4PMKj45XJvCsCh/8h/ZqMuLwLRuTWkr3ILJstqPAiwCcUL4w2wuTUwxwK+mXJ1wq/HIYSbRhVYIPrVSndP2RxOaI2ltdyek73GlrSbtVBO6IIr555iJsSeCcprVa9cFnnkHkoMEoIdJJVzIQZkKPZf/c25rrA5/GrftihA9IA5utIjO9K+qdV6DsNkSaBmU8gevyEojjKk++ZDGXxLgJ9UkmNVwNW8rHwCLgM42MzHoLB2opBvmD/p1ZXt3T4dMvfdQGBDfoxQOHCQJeThEYu40Yb48o/MezMQZxeTeNKiuvl6JF7kO4MdqdPb744RmkslA47AbZ5mpHgwiYJ0QVphyidy+QoAr2ozH+Zu9x6ux4kCwUBc0Y9HzRgJ2xJJ6fef5hci/QXimHEnerzbSTNWnKqs4d0Qk0MlX3nDRQEASMaNn/97Pj46Z0fCs03riUFmamtOOMCoY3I1Q2G5Cfs6PJWzO1Bp0aNtMAmI0LpJFknBYxXxjZLXIKV+WMCaVEupON1hRvOUQPb6VZMS24zfJ6Izxiyd4ImJmOGsFJMiGzCRWHyw8kuQZBUVd09gnbWTDgAyGUzB55vsVmVRsqCVCEiJ4MpHNqCFdb3i5dGhZ53ngqEXyq0GMtTPs//5t5xosiHZKZFAGYwDzDiTVNG8CfrWOfiAVUgizBM4RN5XPQ4Aooq3bkp4xMY2Zdo3mFzdOPPkSiK76lccXujrmajN1OsDwGLTZm+saKP/dysxe6JooAlnPxCXtmsab0im7ETfQvEnyf4y5aaWiiSQ+nulSWH9FAGJOHTb8kDur3vKEZYoVlJLVe/zKUhOUUeqXYqTRRckm01Cwm8fr5fkgVBipxzFTAaLgRCx37zS+l4AbxxH2N/QOYhAagOPyM7GM7+/tpLXiCrJ8wsz72FDMBxaktwQaankJRj2d2Me9dlf3PyFbCMJqmlKMrHEEiuCYscEWjS6NtyfhYFq0lL6Pj71T70iZO10Dp/r6MmcVdVwa3x0hWTsEISnhC1oo81LRKI7EWDY2JOwObWYdTLkWnDMlctCgr+Hj0xVrEARjwPDn10nTs/Xi0khqcCOMPs0zXt,iv:MDc0EuMa1fnUB1v2u4BjaKrgnQnDS1IUaqsIvYal0Es=,tag:ULPp2J7+cXKlH9HeofRscA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdzF2SkpFbDkyTE5nNkY1
            TkhrNTZLVW5hd1RXY2w1bzg5d2s4OUorYURZCjUvdFNjQlhOQ2M1UE9JZWdWV1Iw
            c1lEQWhzR3c3NlVOTGR6d3V5b0U4emMKLS0tIHFhclJlZFRwZlNqbWRpM3lYY1cy
            eUlERWhpUzFOVmNiNkVQTllyUE1oSmcKrvJ7gHiLflfwpvCtWayoX9DEADdhcZ54
            mZTnKZUrFApDChVD8ojWBGtPfQd+LdfHe/aljmFBk6v7qN1hOybGrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jqn3xexdp75t7mgn4nyl3jhnqgsvxmnxpxu3c9x8zs27k439v9yqja32v3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T23:02:18Z"
    mac: ENC[AES256_GCM,data:j2b5bByXlhzLSALz03guhNi6jGxJvhCMsvd2sSbjOrpEw8L6f/L7cxGOAusjpAskn+hfd37qkWfsuZxuW3/AhLAbJKjG8LVfuUDT7yXwC+axNYujzukywwbOXoyIsj3GECEnHIsvLw5l3Kmuj9sST7pfq+h75Ga8G13YFb2prK0=,iv:9Jdcy8364XbsPinjcZvGhri4RlBsJf7naAJnJzgZm68=,tag:Gex32GzjnbWtXVbLySBFlg==,type:str]
    version: 3.13.1
